# Generated by Django 4.2.4 on 2023-09-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lesson_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
    ]
