# Generated by Django 4.2.4 on 2023-09-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='стоимость'),
        ),
    ]
